import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
  isDevMode, LOCALE_ID,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import {
  provideHttpClient,
  withInterceptors
} from '@angular/common/http';
import { OAuthModule, provideOAuthClient } from 'angular-oauth2-oidc';
import { authInterceptor } from '@woodia-core/interceptors/auth.interceptor';
import { provideTransloco } from '@jsverse/transloco';
import { TranslocoHttpLoader } from './transloco-loader';

import localeEn from '@angular/common/locales/en';
import localeAr from '@angular/common/locales/ar';
import { registerLocaleData } from '@angular/common';

registerLocaleData(localeEn);
registerLocaleData(localeAr);


import { provideIcons } from '@ng-icons/core';
import {
  lucideSun,
  lucideMoon,
  lucideMonitor,
  lucideGlobe,
  lucideLanguages,
  lucideX,
  lucidePanelLeft,
  lucidePanelLeftClose,
  lucidePanelRight,
  lucidePanelRightClose,
  lucideMenu,
  lucideChevronRight,
  lucideChevronLeft,
  lucideChevronDown,
  lucideChevronUp,
  lucideHouse,
  lucideArmchair,
  lucideLayoutGrid,
  lucideEye,
  lucideEyeOff,
  lucideArrowLeft,
  lucideArrowRight,
  lucideArrowDown,
  lucideArrowUp,
  lucideCircleUserRound,
  lucideTruck,
  lucideTriangleAlert,
  lucideImageOff,
  lucideImage,
  lucideLogOut,
  lucideLink,
  lucideLink2,
  lucideBell,
  lucideSettings,
  lucideMessagesSquare,
  lucideList,
  lucideGrid,
  lucideCalendar,
  lucideMessageSquare,
  lucideRotateCw,
  lucideRotateCcw,
  lucideBadge,
  lucideCircle,
  lucideLoaderCircle,
  lucideEllipsisVertical,
  lucideEllipsis,
  lucideSave,
  lucideBlocks,
  lucideShoppingBag,
  lucideHammer,
  lucidePencil,
  lucideClipboardList,
  lucideWand2,
  lucideBookOpen,
  lucideBriefcase,
  lucideDollarSign,
  lucideMoreVertical,
  lucideClock,
  lucideAlertCircle,
  lucideRefreshCw,
  lucideEdit3,
  lucideFileText,
  lucideCoins,
  lucideSettings2,
  lucideFileWarning,
  lucideCheck,
} from '@ng-icons/lucide';

export const appConfig: ApplicationConfig = {
  providers: [
    provideIcons({
      lucideSun,
      lucideMoon,
      lucideMonitor,
      lucideGlobe,
      lucideLanguages,
      lucideX,
      lucidePanelLeft,
      lucidePanelLeftClose,
      lucidePanelRight,
      lucidePanelRightClose,
      lucideMenu,
      lucideChevronRight,
      lucideChevronLeft,
      lucideChevronDown,
      lucideChevronUp,
      lucideHouse,
      lucideArmchair,
      lucideLayoutGrid,
      lucideEye,
      lucideEyeOff,
      lucideArrowLeft,
      lucideArrowRight,
      lucideArrowDown,
      lucideArrowUp,
      lucideCircleUserRound,
      lucideTruck,
      lucideTriangleAlert,
      lucideImageOff,
      lucideImage,
      lucideLogOut,
      lucideLink,
      lucideLink2,
      lucideBell,
      lucideSettings,
      lucideMessagesSquare,
      lucideList,
      lucideGrid,
      lucideCalendar,
      lucideMessageSquare,
      lucideRotateCw,
      lucideRotateCcw,
      lucideBadge,
      lucideCircle,
      lucideLoaderCircle,
      lucideEllipsisVertical,
      lucideEllipsis,
      lucideSave,
      lucideBlocks,
      lucideShoppingBag,
      lucideHammer,
      lucidePencil,
      lucideClipboardList,
      lucideWand2,
      lucideBookOpen,
      lucideBriefcase,
      lucideDollarSign,
      lucideMoreVertical,
      lucideClock,
      lucideAlertCircle,
      lucideRefreshCw,
      lucideEdit3,
      lucideFileText,
      lucideCoins,
      lucideSettings2,
      lucideFileWarning,
      lucideCheck,
    }),
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideHttpClient(
      withInterceptors([authInterceptor])
    ),
    importProvidersFrom(OAuthModule.forRoot()),
    provideOAuthClient(),
    { provide: LOCALE_ID, useValue: 'ar' },
    provideTransloco({
      config: {
        availableLangs: ['en', 'ar'],
        defaultLang: 'ar',
        // Remove this option if your application doesn't support changing language in runtime.
        reRenderOnLangChange: true,
        prodMode: !isDevMode(),
      },
      loader: TranslocoHttpLoader,
    }),

  ]
};
